import { FilterPreset } from '../types';

export const FILTER_PRESETS: FilterPreset[] = [
  // --- DEFAULT / NATURAL ---
  {
    id: 'original',
    name: 'Original',
    category: 'all',
    description: 'Clean, unaltered native sensor sensor feed',
    badge: 'RAW',
    shaderUniforms: {
      exposure: 0,
      contrast: 1.0,
      saturation: 1.0,
      temperature: 0,
      tint: 0,
      highlights: 0,
      shadows: 0,
      vignette: 0,
      grain: 0,
      bloom: 0,
      neonBoost: 0,
      clarity: 0,
    }
  },

  // --- 1. MOODY PRESETS ---
  {
    id: 'moody_deep',
    name: 'Moody Noir',
    category: 'moody',
    description: 'Deep shadows, rich contrast, and desaturated melancholic tones',
    badge: 'Popular',
    shaderUniforms: {
      exposure: -0.15,
      contrast: 1.38,
      saturation: 0.72,
      temperature: -0.22,
      tint: 0.1,
      highlights: -0.25,
      shadows: -0.45,
      vignette: 0.42,
      grain: 0.18,
      bloom: 0,
      neonBoost: 0,
      clarity: 0.3,
    }
  },
  {
    id: 'moody_emerald',
    name: 'Dark Emerald',
    category: 'moody',
    description: 'Forest shadow tones with crushed blacks and preserved skin tones',
    badge: 'Cinematic',
    shaderUniforms: {
      exposure: -0.1,
      contrast: 1.25,
      saturation: 0.85,
      temperature: -0.3,
      tint: -0.2,
      highlights: -0.1,
      shadows: -0.35,
      vignette: 0.35,
      grain: 0.12,
      bloom: 0,
      neonBoost: 0,
      clarity: 0.25,
    }
  },
  {
    id: 'moody_amber',
    name: 'Deep Amber',
    category: 'moody',
    description: 'Warm, low-key incandescent moody shadows with rich copper highlights',
    shaderUniforms: {
      exposure: -0.08,
      contrast: 1.3,
      saturation: 0.9,
      temperature: 0.4,
      tint: 0.15,
      highlights: 0.05,
      shadows: -0.4,
      vignette: 0.38,
      grain: 0.15,
      bloom: 0,
      neonBoost: 0,
      clarity: 0.2,
    }
  },

  // --- 2. DREAMY PRESETS ---
  {
    id: 'dreamy_angel',
    name: 'Angel Aura',
    category: 'dreamy',
    description: 'Soft focus, glowing ethereal highlights, and pastel color grading',
    badge: 'Trending',
    shaderUniforms: {
      exposure: 0.18,
      contrast: 0.88,
      saturation: 1.15,
      temperature: 0.18,
      tint: 0.22,
      highlights: 0.35,
      shadows: 0.25,
      vignette: 0.15,
      grain: 0.08,
      bloom: 0.75,
      neonBoost: 0,
      clarity: -0.2,
    }
  },
  {
    id: 'dreamy_golden_haze',
    name: 'Golden Haze',
    category: 'dreamy',
    description: 'Warm sun-drenched diffusion with glowing sunset undertones',
    shaderUniforms: {
      exposure: 0.12,
      contrast: 0.92,
      saturation: 1.2,
      temperature: 0.55,
      tint: 0.1,
      highlights: 0.4,
      shadows: 0.2,
      vignette: 0.2,
      grain: 0.05,
      bloom: 0.65,
      neonBoost: 0,
      clarity: -0.15,
    }
  },
  {
    id: 'dreamy_pastel_mist',
    name: 'Pastel Mist',
    category: 'dreamy',
    description: 'Ultra-soft low-contrast glow with cotton-candy pastel balance',
    shaderUniforms: {
      exposure: 0.22,
      contrast: 0.82,
      saturation: 1.05,
      temperature: -0.1,
      tint: 0.3,
      highlights: 0.3,
      shadows: 0.3,
      vignette: 0.1,
      grain: 0.1,
      bloom: 0.85,
      neonBoost: 0,
      clarity: -0.3,
    }
  },

  // --- 3. NIGHTCORE PRESETS ---
  {
    id: 'nightcore_cyberpunk',
    name: 'Cyberpunk 2077',
    category: 'nightcore',
    description: 'Electric cyan and neon magenta popping colors optimized for low-light nightlife',
    badge: 'Pro Neon',
    shaderUniforms: {
      exposure: 0.05,
      contrast: 1.45,
      saturation: 1.65,
      temperature: -0.4,
      tint: 0.5,
      highlights: 0.2,
      shadows: -0.3,
      vignette: 0.45,
      grain: 0.12,
      bloom: 0.4,
      neonBoost: 0.9,
      clarity: 0.45,
    }
  },
  {
    id: 'nightcore_synthwave',
    name: 'Synthwave Glow',
    category: 'nightcore',
    description: 'Deep purple shadows with hyper-saturated hot pink & laser cyan highlights',
    shaderUniforms: {
      exposure: 0.0,
      contrast: 1.4,
      saturation: 1.75,
      temperature: -0.2,
      tint: 0.65,
      highlights: 0.3,
      shadows: -0.35,
      vignette: 0.5,
      grain: 0.15,
      bloom: 0.5,
      neonBoost: 0.85,
      clarity: 0.4,
    }
  },
  {
    id: 'nightcore_tokyo',
    name: 'Tokyo Neon',
    category: 'nightcore',
    description: 'High dynamic night street aesthetic with intense LED saturation and deep dark alleys',
    shaderUniforms: {
      exposure: 0.08,
      contrast: 1.35,
      saturation: 1.5,
      temperature: -0.35,
      tint: 0.25,
      highlights: 0.25,
      shadows: -0.25,
      vignette: 0.35,
      grain: 0.1,
      bloom: 0.35,
      neonBoost: 0.75,
      clarity: 0.35,
    }
  },

  // --- 4. VIVID PRESETS ---
  {
    id: 'vivid_punch',
    name: 'Ultra Vivid',
    category: 'vivid',
    description: 'Punchy, high-contrast colors that make skies, nature, and everyday scenes pop',
    badge: 'Vibrant',
    shaderUniforms: {
      exposure: 0.05,
      contrast: 1.28,
      saturation: 1.6,
      temperature: 0.08,
      tint: 0.0,
      highlights: 0.1,
      shadows: 0.05,
      vignette: 0.18,
      grain: 0.0,
      bloom: 0.1,
      neonBoost: 0.2,
      clarity: 0.35,
    }
  },
  {
    id: 'vivid_kodak',
    name: 'Kodak Chrome',
    category: 'vivid',
    description: 'Classic rich Kodachrome red/yellow warmth with crisp sky saturation',
    shaderUniforms: {
      exposure: 0.02,
      contrast: 1.32,
      saturation: 1.45,
      temperature: 0.28,
      tint: -0.05,
      highlights: -0.05,
      shadows: -0.15,
      vignette: 0.22,
      grain: 0.1,
      bloom: 0.05,
      neonBoost: 0.15,
      clarity: 0.3,
    }
  },
  {
    id: 'vivid_tropical',
    name: 'Tropical Punch',
    category: 'vivid',
    description: 'Lush oceanic blues and rich emerald greens for travel and landscape photography',
    shaderUniforms: {
      exposure: 0.08,
      contrast: 1.22,
      saturation: 1.55,
      temperature: -0.15,
      tint: -0.15,
      highlights: 0.15,
      shadows: 0.1,
      vignette: 0.15,
      grain: 0.0,
      bloom: 0.1,
      neonBoost: 0.25,
      clarity: 0.25,
    }
  },

  // --- 5. ANALOG FILM PRESETS ---
  {
    id: 'film_portra400',
    name: 'Portra 400',
    category: 'film',
    description: 'Legendary 35mm film emulation with creamy skin tones and organic grain',
    badge: 'Analog',
    shaderUniforms: {
      exposure: 0.04,
      contrast: 1.12,
      saturation: 1.1,
      temperature: 0.18,
      tint: 0.08,
      highlights: 0.1,
      shadows: 0.12,
      vignette: 0.28,
      grain: 0.35,
      bloom: 0.2,
      neonBoost: 0,
      clarity: 0.1,
    }
  },
  {
    id: 'film_cinestill800t',
    name: 'Cinestill 800T',
    category: 'film',
    description: 'Tungsten-balanced night film with distinct red halation glow around point lights',
    shaderUniforms: {
      exposure: 0.0,
      contrast: 1.25,
      saturation: 1.2,
      temperature: -0.32,
      tint: 0.12,
      highlights: 0.25,
      shadows: -0.2,
      vignette: 0.32,
      grain: 0.42,
      bloom: 0.45,
      neonBoost: 0.3,
      clarity: 0.2,
    }
  },

  // --- 6. CINEMATIC PRESETS ---
  {
    id: 'cinematic_teal_orange',
    name: 'Blockbuster 35',
    category: 'cinematic',
    description: 'Hollywood teal shadows and golden orange skin tones for blockbuster storytelling',
    badge: 'Hollywood',
    shaderUniforms: {
      exposure: -0.05,
      contrast: 1.35,
      saturation: 1.35,
      temperature: 0.22,
      tint: -0.18,
      highlights: 0.1,
      shadows: -0.3,
      vignette: 0.4,
      grain: 0.18,
      bloom: 0.15,
      neonBoost: 0.2,
      clarity: 0.35,
    }
  },

  // --- 7. MONOCHROME / B&W PRESETS ---
  {
    id: 'bw_trix',
    name: 'Tri-X B&W',
    category: 'bw',
    description: 'High-contrast street photography monochrome with gritty analog grain',
    badge: 'B&W',
    shaderUniforms: {
      exposure: 0.0,
      contrast: 1.5,
      saturation: 0.0,
      temperature: 0.0,
      tint: 0.0,
      highlights: 0.15,
      shadows: -0.35,
      vignette: 0.35,
      grain: 0.4,
      bloom: 0.0,
      neonBoost: 0.0,
      clarity: 0.45,
    }
  }
];

export const FILTER_CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'moody', label: 'Moody' },
  { id: 'dreamy', label: 'Dreamy' },
  { id: 'nightcore', label: 'Nightcore' },
  { id: 'vivid', label: 'Vivid' },
  { id: 'film', label: 'Film 35mm' },
  { id: 'cinematic', label: 'Cinematic' },
  { id: 'bw', label: 'B&W' },
] as const;
